// Off-screen only — never shown to the user. HARD CONSTRAINT (ADR-0009): every
// style value below must be a literal hex or rgb()/rgba() string. No Tailwind
// className anywhere in this file, no components/ui/button.tsx import.
export interface AttemptPdfTemplateProps {
  examTitle: string;
  totalScore: number;
  submittedDateLabel: string;
  completionTimeLabel: string;
  generatedAtLabel: string;
}

export function AttemptPdfTemplate({
  examTitle,
  totalScore,
  submittedDateLabel,
  completionTimeLabel,
  generatedAtLabel,
}: AttemptPdfTemplateProps) {
  return (
    <div
      style={{
        width: 720,
        backgroundColor: "#ede1c8",
        color: "#1b1512",
        padding: 40,
        fontFamily: "'Be Vietnam Pro', sans-serif",
      }}
    >
      <header style={{ display: "flex", alignItems: "center", gap: 16 }}>
        {/* `<img>` CỐ Ý, không phải sót: template này được html2canvas chụp
            thành ảnh (lib/pdf/generateAttemptPdf.ts). `next/image` render ra
            <img> có srcset + lazy-load + wrapper span — html2canvas chụp
            trước khi ảnh lazy kịp nạp, ra logo trắng trong PDF. Tắt cảnh báo
            tại chỗ để `--max-warnings 0` ở CI còn bắt được cảnh báo MỚI. */}
        {/* eslint-disable-next-line @next/next/no-img-element */}
        <img src="/images/brand_logo.png" width={42} height={38} alt="" />
        <div style={{ width: 40, height: 2, backgroundColor: "#b8863b" }} />
      </header>
      <h1
        style={{
          fontFamily: "'Source Serif 4', serif",
          color: "#1b1512",
          fontSize: 36,
          marginTop: 24,
        }}
      >
        {examTitle}
      </h1>
      <p
        style={{
          fontFamily: "'Source Serif 4', serif",
          color: "#a62c2b",
          fontSize: 64,
          marginTop: 20,
        }}
      >
        {totalScore.toFixed(1)}
        <span style={{ fontSize: 24, color: "#605a52" }}>/10</span>
      </p>
      <p style={{ color: "#605a52", fontSize: 14, marginTop: 24 }}>
        {submittedDateLabel} · {completionTimeLabel}
      </p>
      <div style={{ height: 1, backgroundColor: "#d8c9a8", marginTop: 32 }} />
      <p style={{ color: "#605a52", fontSize: 12, marginTop: 12 }}>
        Generated by MS-MOLAR · summary only, not a full transcript · {generatedAtLabel}
      </p>
    </div>
  );
}
